---
title: "Worksheet2 in R"
author: "Erl Syron R. Espadon"
output: html_document
---

#vector using operator

# a. Sequence from -5 to 5
seq_vector <- -5:5  #output: sequence of integers starting from -5 up to 5
seq_vector 

# b. x <- 1:7, the value of x
x <- 1:7  #output:  a sequence from 1 to 7.
x

# 2. Creating a vector using seq() function

# a. Sequence from 1 to 3 with a step size of 0.2
seq_vector_2 <- seq(1, 3, by=0.2)  #output: a sequence from 1 to 3, with a step size of 0.2
seq_vector_2

# 3. Worker ages vector and accessing specific elements
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 
          49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 
          38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)

# a. Access the 3rd element
ages[3]  #output: 22

# b. Access the 2nd and 4th elements
ages[c(2, 4)]  #output: 28 36

# c. Access all but the 4th and 12th elements
ages[-c(4, 12)]  #output: All except 4th and 12th elements

# 4. Named vector x
x <- c("first" = 3, "second" = 0, "third" = 9)
names(x)
x[c("first", "third")]  #output: names of the vector elements

# 5. Sequence from -3:2 and modifying the second element
x_seq <- -3:2
x_seq[2] <- 0
x_seq   #output: -3  0 -1  0  1  2 

#6.fuel purchase
month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

# a. Create the data frame
fuel_data <- data.frame(month, price_per_liter, purchase_quantity)
fuel_data  #output: Data frame will show the table of months, prices, and quantities.

# b. Calculate the weighted mean
weighted.mean(price_per_liter, purchase_quantity)  #output: average fuel expenditure

#7.Working with built-in datasets (rivers dataset)

#a. Create a vector with specific statistical values for the rivers dataset
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), 
          sd(rivers), min(rivers), max(rivers))
data  #output:length, sum, mean, median, variance, standard deviation, minimum, and maximum of the rivers dataset:

#8. Working with Forbes celebrity rankings

#a. Create vectors according to the table in the worksheet
names <- c("Oprah Winfrey", "Tiger Woods", "Angelina Jolie", "Beyonce Knowles", "David Beckham", 
           "J.K. Rowling", "Brad Pitt", "Johnny Depp", "Jay-Z", "Kobe Bryant")
ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
pay <- c(275, 105, 20, 87, 40, 300, 31, 92, 63, 45)
data <- data.frame(names, ranking, pay)
data

#b. Modify the power ranking and pay of J.K. Rowling (assuming it is the 2nd entry)
data$ranking[2] <- 15
data$pay[2] <- 90
data

#c. Save the table as a CSV file
write.csv(data, "PowerRanking.csv")

#d. Import the CSV and access rows 10 to 20
data <- read.csv("PowerRanking.csv")
subset_data <- data[10:20, ]
save(subset_data, file = "Ranks.RData")


#9. Working with an Excel file (Hotels-Vienna)

#a. Import the Excel file into RStudio
library(readxl)
hotels_data <- read_excel("C:\\Users\\Acer\\Downloads\\hotels-vienna.xlsx")

#b. How many dimensions does the dataset have?
dim(hotels_data)  #output: This will return the number of rows and columns (500 rows, 7 columns)

#Select specific columns:
selected_hotels <- hotels_data[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]  
print(selected_hotels)

#d. Save the data as new.RData:
save(selected_hotels, file = "new.RData")

#e. Display the first and last 6 rows of new.RData:
print(head(selected_hotels))
print(tail(selected_hotels)) #output: first 6 and last 6 rows of the dataset.

#10. Working with lists of vegetables:

#a. Create a list of 10 vegetables:
vegetables <- c("Carrot", "Broccoli", "Spinach", "Tomato", "Cucumber", "Pepper", "Onion", "Garlic", "Potato", "Lettuce")
print(vegetables)

# b. Add 2 more vegetables
vegetables <- c(vegetables, "Pumpkin", "Zucchini")
print(vegetables)

# c. Add 4 more vegetables after the 5th index
vegetables <- append(vegetables, c("Eggplant", "Radish", "Mushroom", "Beetroot"), after = 5)
print(vegetables) 

# How many vegetables?
print(length(vegetables))  #output: This will return the number of data points


# d. Remove vegetables at indices 5, 10, and 15
vegetables <- vegetables[-c(5, 10, 15)]
print(vegetables)

# How many vegetables left?
print(length(vegetables))  #output: # This will return the remaining number of vegetables

